//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuriborSharp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class EuriborSharpSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EuriborSharpSettings defaultInstance = ((EuriborSharpSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EuriborSharpSettings())));
        
        public static EuriborSharpSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.suomenpankki.fi/fi/_layouts/BOF/RSS.ashx/tilastot/Korot/fi")]
        public string RssFeedAddress {
            get {
                return ((string)(this["RssFeedAddress"]));
            }
            set {
                this["RssFeedAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothLine {
            get {
                return ((bool)(this["SmoothLine"]));
            }
            set {
                this["SmoothLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DotLineSelected {
            get {
                return ((bool)(this["DotLineSelected"]));
            }
            set {
                this["DotLineSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NormalLineSelected {
            get {
                return ((bool)(this["NormalLineSelected"]));
            }
            set {
                this["NormalLineSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Line")]
        public global::EuriborSharp.Enums.GraphStyle SelectedGraphStyle {
            get {
                return ((global::EuriborSharp.Enums.GraphStyle)(this["SelectedGraphStyle"]));
            }
            set {
                this["SelectedGraphStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autoload {
            get {
                return ((bool)(this["Autoload"]));
            }
            set {
                this["Autoload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::EuriborSharp.Enums.Renderer SelectedRenderer {
            get {
                return ((global::EuriborSharp.Enums.Renderer)(this["SelectedRenderer"]));
            }
            set {
                this["SelectedRenderer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XkcdSelected {
            get {
                return ((bool)(this["XkcdSelected"]));
            }
            set {
                this["XkcdSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.emmi-benchmarks.eu/assets/modules/rateisblue/processed_files/hist_EURI" +
            "BOR_2015.csv")]
        public string EuriborDefaultUrl {
            get {
                return ((string)(this["EuriborDefaultUrl"]));
            }
            set {
                this["EuriborDefaultUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:00:00")]
        public global::System.TimeSpan UpdateInterval {
            get {
                return ((global::System.TimeSpan)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
    }
}
